### ISSUE TITLE
Plans to add a "stock" sink module?

### ISSUE THREAD

**Issue by cboggs** [ferd/vmstats#13]
Are there any plans to include a basic stock sink module to write to StatsD or something? Since the previous releases depended on statsderl, it seems like at least a small basic module that can offload to statsderl would be a handy inclusion. Still configurable and not required, of course, so that there wouldn't be a hard dependency on statsderl, but available as an easy option.

Just curious. :-) Thanks!

**Comment by ferd** [comment]
https://github.com/elixir-addicts/vmstats_statsderl this would be the thing you are looking for I believe.

**Comment by cboggs** [comment]
:facepalm:

I didn't even think to look OUTSIDE this repo. Thanks for humoring me! :-)
