### ISSUE TITLE
Atom count

### ISSUE THREAD

**Issue by Coffei** [ferd/vmstats#16]
Hi,
currently vmstats doesn't report the number of atoms in the VM, only the memory used by those atoms. Since erlang 20 there is a call to get the number of atoms in the system (`erlang:system_info(atom_count).
`).

Would you be interested in a PR to add this metric? It would only work on erlang 20+, but I think it's better to have it available when the system supports it rather than not having it everywhere.

**Comment by ferd** [comment]
As long as it's backwards compatible (i.e. older systems don't suddenly start failing if they upgrade vmstats) then I think it's fine.

**Comment by Coffei** [comment]
Great, have the fix but will test it some more tomorrow and if all goes well send a PR.

**Comment by Coffei** [comment]
Closing, as we resolved this in #17.
