### ISSUE TITLE
Possible bug getting error_logger stats on OTP 21

### ISSUE THREAD

**Issue by uberbrodt** [ferd/vmstats#20]
Hi, I was testing out OTP 21.0 and it seems like the logger changes they made are causing an error in vmstats_server:
```
** (ArgumentError) argument error
    :erlang.process_info(:undefined, :message_queue_len)
    (vmstats) /home/cbrodt/Projects/traitify/profile-svc/profile_service/deps/vmstats/src/vmstats_server.erl:98: :vmstats_server.handle_info/2
````

The above is from an Elixir project, but I don't think that should make a difference here. I got the error on both vmstats 2.2 and 2.3. The above message is from running with 2.3.

**Comment by ferd** [comment]
yeah error_logger no longer exists. That metric should be disabled for OTP-21.

**Comment by hauleth** [comment]
@ferd `error_logger` exists, but isn't started by default. That is why in proposed solution I dynamically check if it is running and then handle it accordingly. So this metric also can happen to be available in OTP-21, but not always.

**Comment by ferd** [comment]
A new version has been tagged and also published to hex
