### ISSUE TITLE
BEAM uptime stats.

### ISSUE THREAD

**Issue by shymega** [ferd/vmstats#24]
Hello,

I've been working on a PR locally on my machine to provide statistics of the time the BEAM VM has been running. 

The code I am using to find the BEAM uptime (in milliseconds) is: `element(1, erlang:statistics(wall_clock))`. I was wondering if this PR would be accepted?

I haven't got `vmstats` integrated with the uptime function as of yet, but I am getting there :)

Thanks!

**Comment by shymega** [comment]
Glad to hear it. My next step now is to get `vmstats_server.erl` to support my BEAM uptime function. I was going to use the `counter` type for the BEAM uptime source.

Is there a particular way new sources should be added to `vmstats`? I haven't found documentation on that at the moment though.

**Comment by ferd** [comment]
Ideally `vmstats` wouldn't have explicit dependencies added, so I'd probably make a more private function. I'm not quite sure what you mean by "new sources" otherwise. Mostly the library just calls functions exposed by the VM to make everything work.

**Comment by shymega** [comment]
Yeah, there's no dependencies in the change. What I've done is this:

```
%% VM uptime .
Sink:collect(timing, [K, "vm_uptime"], erlang:element(1, erlang:statistics(wall_clock))),
```

It will output in milliseconds, and I've got it to use the `timing` type. Is that OK, or should I change it to `gauge`/`counter`? I think that `timing` appears to make sense however.

What I said about "new sources" - just ignore it for now, I got confused with the code - but I understand it now :D

**Comment by shymega** [comment]
I've just made a PR for this addition to `vmstats`. I would like to propose that discussion about the types used is continued on the PR itself, and this issue can be closed when/if the PR is merged or not :)

**Comment by shymega** [comment]
Glad to see #25 got merged. What was the status of adding a `gauge` counter for the VM uptime as well? I was going to call it `vm_uptime_g` in terms of the name. I can make a PR for that as well.

**Comment by ferd** [comment]
Nah I think just one of them is fine. No need to add the same metric twice.

**Comment by shymega** [comment]
Agreed, sounds good to me. The README needs to be updated to list the new metric, and potentially a new release to Hex.pm to include the new metric, but other than that, this issue can be closed :+1:
