### ISSUE TITLE
Timeout errors when starting

### ISSUE THREAD

**Issue by rupurt** [ferd/vmstats#26]
Howdy,

I'm trying to use `vmstats` in my Elixir app and it works with the default sample time of `1000ms` but throws an error on startup.

```
018-10-21T02:36:45.102 [error] GenServer :vmstats_server terminating
** (ArgumentError) argument error
    :erlang.port_command(MyApp.Statix, [<<1, 31, 189, 127, 0, 0, 1, 115, 116, 114, 97, 116, 101, 103, 105, 101, 115, 95, 100, 101, 118, 46>>, [['vmstats', 46], 'proc_count'], 58, "110", 124, "g"])
    (statix) lib/statix/conn.ex:30: Statix.Conn.transmit/2
    (vmstats) /Users/alex/workspace/alex/my_app/deps/vmstats/src/vmstats_server.erl:64: :vmstats_server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:timeout, #Reference<0.1156415048.4132700161.49184>, :"#interval"}
State: {:state, MyApp.VmStatsSink, ['vmstats', 46], 46, [total: :total, processes_used: :procs_used, atom_used: :atom_used, binary: :binary, ets: :ets], :enabled, [{1, 9000, 10000}, {2, 1000, 10000}, {3, 3000, 11000}, {4, 3000, 11000
}, {5, 3000, 11000}, {6, 6000, 10000}, {7, 2000, 10000}, {8, 2000, 10000}, {9, 40000, 646757000}, {10, 23000, 646757000}, {11, 64000, 646757000}, {12, 69000, 646758000}, {13, 10000, 646758000}, {14, 22000, 646758000}, {15, 10000, 64675800
0}, {16, 10000, 646758000}], #Reference<0.1156415048.4132700161.49184>, 100, {176, 95}, {2833, 8996083}}
```

If I reduce the sample time to something like `100ms` I get a bunch of these errors and the application fails to start. I think `vmstats` is trying to sample before my application has started. Do you have any recommendations on how to avoid this? Does there need to be some sort of delay until `vmstats` starts sampling?

Cheers

**Comment by ferd** [comment]
I would probably advise to start vmstats _after_ your reporting app is booted, since it's the one timing out. In Erlang this is often done by specifying your app before vmstats in the relx declaration, but I don't know how that works in Elixir.

An alternative strategy would be not to make the reporting use a synchronous call, and instead use a cast.

**Comment by rupurt** [comment]
@ferd cheers. I added them to the `applications` key in `mix.exs` to control the boot order.
